return require('packer').startup(function()
  use "wbthomason/packer.nvim"

  use "folke/tokyonight.nvim"
  use "rose-pine/neovim"
  use "olimorris/onedarkpro.nvim"
  use "ellisonleao/gruvbox.nvim"
  use "Mofiqul/dracula.nvim"

  use "JuliaEditorSupport/julia-vim"
  use "lervag/vimtex"
  use "tpope/vim-surround"
  use "tpope/vim-commentary"
  use "AndrewRadev/switch.vim"
  use ("nvim-treesitter/nvim-treesitter", {run = ':TSUpdate'})
  use "nvim-treesitter/playground"
  use "nvim-lualine/lualine.nvim"
  use "onsails/lspkind.nvim"
  use "windwp/nvim-autopairs"
  use "windwp/nvim-ts-autotag"
  use "hrsh7th/nvim-cmp"
  use "hrsh7th/cmp-buffer"
  use "hrsh7th/cmp-nvim-lsp"
  use "hrsh7th/cmp-path"
  use "saadparwaiz1/cmp_luasnip"
  use "L3MON4D3/LuaSnip"
  use "rafamadriz/friendly-snippets"
  use "neovim/nvim-lspconfig"
  use "jose-elias-alvarez/null-ls.nvim"
  use "MunifTanjim/prettier.nvim"
  use "glepnir/lspsaga.nvim"
  use "mbbill/undotree"

  use "nvim-lua/plenary.nvim"
  use "nvim-telescope/telescope.nvim"
  use "nvim-telescope/telescope-file-browser.nvim"
  use "kyazdani42/nvim-web-devicons"

  use "norcalli/nvim-colorizer.lua"
  use "lewis6991/gitsigns.nvim"
  use "dinhhuy258/git.nvim"
  use "lukas-reineke/indent-blankline.nvim"
end)
